/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { JobDescription } from "./JobDescription";
import { JobDescriptionCountArgs } from "./JobDescriptionCountArgs";
import { JobDescriptionFindManyArgs } from "./JobDescriptionFindManyArgs";
import { JobDescriptionFindUniqueArgs } from "./JobDescriptionFindUniqueArgs";
import { CreateJobDescriptionArgs } from "./CreateJobDescriptionArgs";
import { UpdateJobDescriptionArgs } from "./UpdateJobDescriptionArgs";
import { DeleteJobDescriptionArgs } from "./DeleteJobDescriptionArgs";
import { ScanResultFindManyArgs } from "../../scanResult/base/ScanResultFindManyArgs";
import { ScanResult } from "../../scanResult/base/ScanResult";
import { JobDescriptionService } from "../jobDescription.service";
@graphql.Resolver(() => JobDescription)
export class JobDescriptionResolverBase {
  constructor(protected readonly service: JobDescriptionService) {}

  async _jobDescriptionsMeta(
    @graphql.Args() args: JobDescriptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [JobDescription])
  async jobDescriptions(
    @graphql.Args() args: JobDescriptionFindManyArgs
  ): Promise<JobDescription[]> {
    return this.service.jobDescriptions(args);
  }

  @graphql.Query(() => JobDescription, { nullable: true })
  async jobDescription(
    @graphql.Args() args: JobDescriptionFindUniqueArgs
  ): Promise<JobDescription | null> {
    const result = await this.service.jobDescription(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => JobDescription)
  async createJobDescription(
    @graphql.Args() args: CreateJobDescriptionArgs
  ): Promise<JobDescription> {
    return await this.service.createJobDescription({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => JobDescription)
  async updateJobDescription(
    @graphql.Args() args: UpdateJobDescriptionArgs
  ): Promise<JobDescription | null> {
    try {
      return await this.service.updateJobDescription({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => JobDescription)
  async deleteJobDescription(
    @graphql.Args() args: DeleteJobDescriptionArgs
  ): Promise<JobDescription | null> {
    try {
      return await this.service.deleteJobDescription(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ScanResult], { name: "scanResults" })
  async findScanResults(
    @graphql.Parent() parent: JobDescription,
    @graphql.Args() args: ScanResultFindManyArgs
  ): Promise<ScanResult[]> {
    const results = await this.service.findScanResults(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
