/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { JobDescriptionService } from "../jobDescription.service";
import { JobDescriptionCreateInput } from "./JobDescriptionCreateInput";
import { JobDescription } from "./JobDescription";
import { JobDescriptionFindManyArgs } from "./JobDescriptionFindManyArgs";
import { JobDescriptionWhereUniqueInput } from "./JobDescriptionWhereUniqueInput";
import { JobDescriptionUpdateInput } from "./JobDescriptionUpdateInput";
import { ScanResultFindManyArgs } from "../../scanResult/base/ScanResultFindManyArgs";
import { ScanResult } from "../../scanResult/base/ScanResult";
import { ScanResultWhereUniqueInput } from "../../scanResult/base/ScanResultWhereUniqueInput";

export class JobDescriptionControllerBase {
  constructor(protected readonly service: JobDescriptionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobDescription })
  async createJobDescription(
    @common.Body() data: JobDescriptionCreateInput
  ): Promise<JobDescription> {
    return await this.service.createJobDescription({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        location: true,
        title: true,
        postedDate: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [JobDescription] })
  @ApiNestedQuery(JobDescriptionFindManyArgs)
  async jobDescriptions(
    @common.Req() request: Request
  ): Promise<JobDescription[]> {
    const args = plainToClass(JobDescriptionFindManyArgs, request.query);
    return this.service.jobDescriptions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        location: true,
        title: true,
        postedDate: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobDescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async jobDescription(
    @common.Param() params: JobDescriptionWhereUniqueInput
  ): Promise<JobDescription | null> {
    const result = await this.service.jobDescription({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        location: true,
        title: true,
        postedDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobDescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateJobDescription(
    @common.Param() params: JobDescriptionWhereUniqueInput,
    @common.Body() data: JobDescriptionUpdateInput
  ): Promise<JobDescription | null> {
    try {
      return await this.service.updateJobDescription({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          location: true,
          title: true,
          postedDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobDescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteJobDescription(
    @common.Param() params: JobDescriptionWhereUniqueInput
  ): Promise<JobDescription | null> {
    try {
      return await this.service.deleteJobDescription({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          location: true,
          title: true,
          postedDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/scanResults")
  @ApiNestedQuery(ScanResultFindManyArgs)
  async findScanResults(
    @common.Req() request: Request,
    @common.Param() params: JobDescriptionWhereUniqueInput
  ): Promise<ScanResult[]> {
    const query = plainToClass(ScanResultFindManyArgs, request.query);
    const results = await this.service.findScanResults(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        overallScore: true,
        skillsMatchScore: true,
        experienceMatchScore: true,
        educationMatchScore: true,
        formattingScore: true,

        resume: {
          select: {
            id: true,
          },
        },

        jobDescription: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/scanResults")
  async connectScanResults(
    @common.Param() params: JobDescriptionWhereUniqueInput,
    @common.Body() body: ScanResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scanResults: {
        connect: body,
      },
    };
    await this.service.updateJobDescription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/scanResults")
  async updateScanResults(
    @common.Param() params: JobDescriptionWhereUniqueInput,
    @common.Body() body: ScanResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scanResults: {
        set: body,
      },
    };
    await this.service.updateJobDescription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/scanResults")
  async disconnectScanResults(
    @common.Param() params: JobDescriptionWhereUniqueInput,
    @common.Body() body: ScanResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scanResults: {
        disconnect: body,
      },
    };
    await this.service.updateJobDescription({
      where: params,
      data,
      select: { id: true },
    });
  }
}
