/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsInt, Min, Max, IsOptional, ValidateNested } from "class-validator";
import { ResumeWhereUniqueInput } from "../../resume/base/ResumeWhereUniqueInput";
import { Type } from "class-transformer";
import { JobDescriptionWhereUniqueInput } from "../../jobDescription/base/JobDescriptionWhereUniqueInput";

@InputType()
class ScanResultCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  overallScore?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  skillsMatchScore?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  experienceMatchScore?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  educationMatchScore?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  formattingScore?: number | null;

  @ApiProperty({
    required: false,
    type: () => ResumeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResumeWhereUniqueInput)
  @IsOptional()
  @Field(() => ResumeWhereUniqueInput, {
    nullable: true,
  })
  resume?: ResumeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => JobDescriptionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => JobDescriptionWhereUniqueInput)
  @IsOptional()
  @Field(() => JobDescriptionWhereUniqueInput, {
    nullable: true,
  })
  jobDescription?: JobDescriptionWhereUniqueInput | null;
}

export { ScanResultCreateInput as ScanResultCreateInput };
