/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ResumeWhereUniqueInput } from "../../resume/base/ResumeWhereUniqueInput";
import { JobDescriptionWhereUniqueInput } from "../../jobDescription/base/JobDescriptionWhereUniqueInput";

@InputType()
class ScanResultWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  overallScore?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  skillsMatchScore?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  experienceMatchScore?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  educationMatchScore?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  formattingScore?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ResumeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResumeWhereUniqueInput)
  @IsOptional()
  @Field(() => ResumeWhereUniqueInput, {
    nullable: true,
  })
  resume?: ResumeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => JobDescriptionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => JobDescriptionWhereUniqueInput)
  @IsOptional()
  @Field(() => JobDescriptionWhereUniqueInput, {
    nullable: true,
  })
  jobDescription?: JobDescriptionWhereUniqueInput;
}

export { ScanResultWhereInput as ScanResultWhereInput };
